name: Simple-Case
version: 1.0-INDEV
main: pl.polardev.scase.CasePlugin
api-version: 1.21
author: PolarDev
description: Simple crate plugin for Minecraft servers

commands:
  admincase:
    description: Admin commands for managing crates
    usage: /admincase <create|edit|delete|setkey|givekey>
    permission: simplecase.admin
    aliases: [ac, case]

permissions:
  simplecase.admin:
    description: Allows access to admin crate commands
    default: op
